---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  port:
  - port: 31001
    nodePort:31001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app:  helloworld
  type: NodePort
